#!/bin/sh

apt-get install -y vim \
                   ed \
                   git \
                   mercurial \
                   subversion \
                   python3 \
                   python-pip \
                   ssh \
                   openssh-server \
                   alpine \
                   automake \
                   bash \
                   bpython \
                   cloc \
                   dict \
                   aspell \
                   fakeroot \
                   ftp \
                   g++ \
                   gcc \
                   git-flow \
                   gnupg \
                   gnupg-agent \
                   grep \
                   bz2 \
                   gzip \
                   gzip \
                   htop \
                   html2text \
                   imagemagick \
                   irssi \
                   java-common \
                   javascript-common \
                   keypassx \
                   keychain \
                   less \
                   linux-headers-generic \
                   lsof \
                   lynx \
                   tmux \
                   make \
                   mono-runtime \
                   mono-xbuild \
                   mono-gac \
                   openssh-client \
                   openssh-server \
                   patch \
                   perl \
                   proxychains \
                   pypy \
                   python-imaging \
                   python-imaging-tk \
                   python-lxml \
                   python-six \
                   python-tk \
                   python3.3 \
                   rsync \
                   ruby1.8 \
                   sed \
                   awk \
                   sqlite3 \
                   sqlitebrowser \
                   sqlite \
                   sshfs \
                   tmux \
                   unzip \
                   unrar \
                   vagrant \
                   virtualbox \
                   virtualbox-guest-additions \
                   vlock \
                   wget \
                   zsh
